### PR TITLE
fixed typo; expanded command

### PR DESCRIPTION
**Pull request by luclu**
npm i / npm install

### CODE REVIEW

**Comment by Adam-Goldman7** [comment]
hey @luclu 
thanks for pointing that out :)

r u using parity and the status page?

**Comment by luclu** [comment]
only parity atm. Is it curiousity or did I miss something? :)

**Comment by Adam-Goldman7** [comment]
Curiosity
the readme page is going to be redone soon so I'm closing thie PR for now

thanks for contributing!

**Comment by luclu** [comment]
Though so ;)

**Pull request closed without merging**
