### PR TITLE
add deploy to gh-pages script

### PR DESCRIPTION
**Pull request by Adam-Goldman7**
(hopefully) resloves #62

### CODE REVIEW

**Comment by tomusdrw** [comment]
Awesome! :+1:

**Comment by Adam-Goldman7** [comment]
@tomusdrw 
there r 2 ways of doing this

- adding github token to .travis.yml
PROS: simple, no extra file
CONS: github token is at account level, not repo

2. adding deploy_key to the repo
PROS: deploy key is at repo level
CONS: requires adding deploy_key.enc file to repo

I prefer method 1

**Comment by tomusdrw** [comment]
Doesn't matter for me :)

**Comment by Adam-Goldman7** [comment]
Cool :)
so I need an ethcore github access token with public repo privliges

or for someone to add the encryption of it to .travis.yml

**Comment by Adam-Goldman7** [comment]
resolves #66 

need to add encrypted github token wit public repo access to travis yml before merging

@tomusdrw who has ethcore settings access?

**Pull request merged**
