### PR TITLE
state as part of class body

### PR DESCRIPTION
**Pull request by jacogr**
move all state definitions out of the constructor and into the class body

### CODE REVIEW

**Comment by goldylucks** [comment]
about this:
> re-instate stat = {} to chase down nightwatch failure

1. can u elaborate on that?
2. if it's only for tests, IMO it's better to monkey patch react component with state = {}

**Comment by jacogr** [comment]
Don't like that one at all - this is an example of the failing builds 

https://travis-ci.org/jacogr/eth-node-status-page/builds/132318093

I cannot see what causes it exactly, the tests that fail don't seem to point directly to the specific components.

**Comment by jacogr** [comment]
In all cases `this.state.<someVariable>` is used before `this.setState` is called. It doesn't get initialised by default to be an empty object it would seem.

**Comment by tomusdrw** [comment]
Yup. By default `state` is undefined.

**Comment by goldylucks** [comment]
so what u think about monkey patching just for tests?

**Comment by tomusdrw** [comment]
But why only for tests? It should just fail everywhere if state is not defined. I think it just needs to be there.

Does it fail only in tests?

**Comment by jacogr** [comment]
I wouldn't monkey-patch for tests, since it does fail when running as well. (I just saw it via tests first)

My only concern with this currently is that I would like to find another way of getting to these, since the failing tests doesn't give much info as to the route of the problem. Apart from that, the actual cause does make logical sense.

**Comment by goldylucks** [comment]
ohhh I thought only tests fail because of the commits' names
`	state = {} for failing nightwatch tests`

cool, merging :)

**Pull request merged**
